apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1%
      maxUnavailable: 1%
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: frontweb
        image: ilkiformation/apache:v1
        ports:
          - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /var/www/simpleweb/config
          - name: vhost
            mountPath: /etc/apache2/sites-available/
          - name: html
            mountPath: /var/www/simpleweb/
          - name: css
            mountPath: /var/www/simpleweb/css/
          - name: templates
            mountPath: /var/www/simpleweb/templates
      volumes:
        - name: vhost
          configMap:
            name: frontweb-vhost
        - name: html
          configMap:
            name: frontweb-html
        - name: css
          configMap:
            name: frontweb-css
        - name: templates
          configMap:
            name: frontweb-templates
        - name: config
          configMap:
            name: frontweb-config

