apiVersion: v1
data:
  config.php: PD9waHAKCi8qKgogKiBDb25maWd1cmF0aW9uIGZvciBkYXRhYmFzZSBjb25uZWN0aW9uCiAqCiAqLwoKJGhvc3QgICAgICAgPSAic2ltcGxld2ViLWJkZCI7CiR1c2VybmFtZSAgID0gInJvb3QiOwokcGFzc3dvcmQgICA9ICJhemVydHkiOwokZGJuYW1lICAgICA9ICJ0ZXN0IjsKJGRzbiAgICAgICAgPSAibXlzcWw6aG9zdD0kaG9zdDtkYm5hbWU9JGRibmFtZSI7CiRvcHRpb25zICAgID0gYXJyYXkoCiAgICAgICAgICAgICAgICBQRE86OkFUVFJfRVJSTU9ERSA9PiBQRE86OkVSUk1PREVfRVhDRVBUSU9OCiAgICAgICAgICAgICAgKTsK
kind: Secret
metadata:
  creationTimestamp: null
  name: frontweb-config