apiVersion: v1
kind: Pod
metadata:
  name: chuck
  labels:
    app: fortune
spec:
  containers:
  - name: web
    image: ilkiformation/webapache:v1
    ports:
      - containerPort: 80
      - containerPort: 22
  - name: generator
    image: ilkiformation/chuckgen:v1
